I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 126, in script
    with noveinleft
  File "game/script.rpy", line 126, in <module>
    with noveinleft
NameError: name 'noveinleft' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 126, in script
    with noveinleft
  File "/Applications/renpy-8.2.1-sdk/renpy/ast.py", line 1356, in execute
    trans = renpy.python.py_eval(self.expr)
  File "/Applications/renpy-8.2.1-sdk/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Applications/renpy-8.2.1-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 126, in <module>
    with noveinleft
NameError: name 'noveinleft' is not defined

macOS-10.15.7-x86_64-i386-64bit x86_64
Ren'Py 8.2.1.24030407
Attack Berlin v0.2 0.2
Tue Mar  5 19:03:24 2024
